/**
 * Run the tests declared in a DesignGraph against a candidate function body.
 *
 * The workflow is:
 *   1. `materializeWithOverride` renders the graph into a file set, but
 *      swaps in the candidate body for the target function. Pure.
 *   2. `runTests` writes that file set to a temp dir and shells out to
 *      vitest, returning a structured pass/fail summary.
 *
 * Split so most tests can exercise the pure path without touching vitest.
 */

import { spawn } from "node:child_process";
import { mkdtemp, mkdir, writeFile, rm, symlink } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import type { DesignGraph } from "./design-graph.js";
import { debug } from "./debug.js";

export interface CandidateBody {
  module: string;
  name: string;
  body: string;
}

export interface TestRunResult {
  ok: boolean;
  passed: number;
  failed: number;
  output: string;
  /** Stable, sorted list of fully-qualified failing test names. Used by
   *  the dispatcher to detect semantic stagnation — when the SAME set
   *  of tests fails across attempts, the Implementer isn't converging
   *  even if the error text wording differs. Optional for back-compat
   *  with older mocks; absent means "unknown." */
  failingTestNames?: string[];
  /** Map of fully-qualified test name → full `failureMessages[0]` text
   *  including the stack trace. Surfaced to the Implementer on request
   *  via the `stack-trace` info channel. Optional for back-compat. */
  fullFailureMessages?: Map<string, string>;
}

export function materializeWithOverride(
  graph: DesignGraph,
  candidate: CandidateBody,
): Record<string, string> {
  // Delegates to graph.materialize(override) which substitutes in the
  // render step without touching the stored node — safe under concurrent
  // test_run / design_finalize calls sharing the same graph.
  return graph.materialize(candidate);
}

export interface RunTestsOptions {
  /** Override the temp dir root (mainly for debugging). */
  tmpRoot?: string;
  /** Hard timeout for the vitest subprocess. */
  timeoutMs?: number;
  /** Working directory the vitest subprocess is spawned in. Defaults to cwd. */
  cwd?: string;
  /**
   * Reuse this specific directory as the project root instead of
   * creating a fresh tmpdir per call. When provided, the caller owns
   * the lifecycle — the dir is kept across invocations so vitest's
   * incremental cache can warm up (5–10× faster attempts). The caller
   * must `rm -r` when finished.
   */
  projectDir?: string;
}

/**
 * Persistent project scratch directory. A single `ProjectDir` is shared
 * across every dispatch attempt in one `design_plan` / `design_build`
 * invocation, letting vitest reuse its compiled-module cache instead
 * of a cold TS transform every run.
 */
export interface ProjectDir {
  path: string;
  dispose(): Promise<void>;
}

/**
 * Create a persistent project directory — materialize the full graph
 * once, keep the package.json/tsconfig/ctx.ts/etc. warm across calls.
 * The caller must `await dir.dispose()` when the build finishes.
 */
export async function createProjectDir(
  graph: DesignGraph,
  options: { tmpRoot?: string } = {},
): Promise<ProjectDir> {
  const tmpRoot = options.tmpRoot ?? tmpdir();
  const dir = await mkdtemp(path.join(tmpRoot, "rlm-project-"));
  debug("testrun", `created persistent project dir ${dir}`);
  const framework = graph.getProjectConfig()?.testFramework ?? "vitest";
  await writeScaffolding(dir, framework);
  const files = graph.materialize();
  for (const [rel, content] of Object.entries(files)) {
    const full = path.join(dir, rel);
    await mkdir(path.dirname(full), { recursive: true });
    await writeFile(full, content, "utf8");
  }
  return {
    path: dir,
    async dispose() {
      debug("testrun", `disposing project dir ${dir}`);
      await rm(dir, { recursive: true, force: true });
    },
  };
}

async function writeScaffolding(
  dir: string,
  framework: "vitest" | "jest" = "vitest",
): Promise<void> {
  await writeFile(
    path.join(dir, "package.json"),
    JSON.stringify({ name: "rlm-test", type: "module", private: true }),
    "utf8",
  );
  // Jest needs explicit config; vitest auto-discovers. Without a
  // jest.config, `npx jest --rootDir <dir>` reports "No tests found"
  // which looks identical to a load failure in our output.
  if (framework === "jest") {
    await writeFile(
      path.join(dir, "jest.config.js"),
      `// Auto-generated by the RLM harness.\nexport default {\n  testEnvironment: "node",\n  testMatch: ["**/*.test.ts"],\n  transform: {\n    "^.+\\\\.tsx?$": ["ts-jest", { useESM: true }]\n  },\n  extensionsToTreatAsEsm: [".ts"],\n};\n`,
      "utf8",
    );
  }
  await writeFile(
    path.join(dir, "tsconfig.json"),
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "Bundler",
          strict: false,
          noEmit: true,
          skipLibCheck: true,
          esModuleInterop: true,
          allowImportingTsExtensions: true,
          types: ["node"],
        },
        include: ["**/*.ts"],
      },
      null,
      2,
    ),
    "utf8",
  );
  // Symlink the host's node_modules so @types/node (and any other
  // dev-deps) are resolvable from the temp dir. Without this, Node
  // built-ins (`fs`, `http`, `IncomingMessage`) are unresolved and
  // vitest's ts transform rejects the test file, yielding a bogus
  // 0/0 pass-through we can't distinguish from "no tests matched."
  const hostNodeModules = path.join(process.cwd(), "node_modules");
  const targetNodeModules = path.join(dir, "node_modules");
  try {
    await symlink(hostNodeModules, targetNodeModules, "dir");
  } catch (e) {
    debug(
      "testrun",
      `could not symlink node_modules: ${e instanceof Error ? e.message : String(e)}`,
    );
  }
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export async function runTests(
  graph: DesignGraph,
  candidate: CandidateBody,
  options: RunTestsOptions = {},
): Promise<TestRunResult> {
  debug(
    "testrun",
    `${candidate.module}#${candidate.name} body=${candidate.body.length}ch`,
  );
  const files = materializeWithOverride(graph, candidate);
  const target = graph.getFunction(candidate.module, candidate.name);
  const hasTests = target !== undefined && target.tests.length > 0;
  const nameFilter = `^${escapeRegex(candidate.name)}\\b`;
  // Test framework is a project-level choice made in phase 0. If phase
  // 0 didn't run (manual graphs in tests, resume from old disk state),
  // default to vitest to preserve previous behavior.
  const framework = graph.getProjectConfig()?.testFramework ?? "vitest";
  // Persistent-dir path: the caller manages lifecycle. Rewrite ALL
  // emitted files (not just the target's) so siblings' just-committed
  // implementations reach disk — a dispatch dependent (ordered after
  // its dep in topo sort) must see the dep's green body, not the stub
  // that was on disk at init time. Writing N small files is cheap
  // compared to a vitest run.
  if (options.projectDir) {
    const dir = options.projectDir;
    for (const [rel, content] of Object.entries(files)) {
      const full = path.join(dir, rel);
      await mkdir(path.dirname(full), { recursive: true });
      await writeFile(full, content, "utf8");
    }
    debug(
      "testrun",
      `reused project dir ${dir} — rewrote ${Object.keys(files).length} files`,
    );
    const result = await invokeTestRunner(
      dir,
      options,
      hasTests,
      framework,
      nameFilter,
    );
    debug(
      "testrun",
      `result ${candidate.module}#${candidate.name} ok=${result.ok} passed=${result.passed} failed=${result.failed}`,
    );
    return result;
  }

  // Cold path: one-shot tmp dir per call (same contract as before).
  const tmpRoot = options.tmpRoot ?? tmpdir();
  const dir = await mkdtemp(path.join(tmpRoot, "rlm-test-"));
  try {
    await writeScaffolding(dir, framework);
    for (const [rel, content] of Object.entries(files)) {
      const full = path.join(dir, rel);
      await mkdir(path.dirname(full), { recursive: true });
      await writeFile(full, content, "utf8");
    }
    debug(
      "testrun",
      `materialized ${Object.keys(files).length} files to ${dir} hasTests=${hasTests} filter=${nameFilter}`,
    );
    const result = await invokeTestRunner(
      dir,
      options,
      hasTests,
      framework,
      nameFilter,
    );
    debug(
      "testrun",
      `result ${candidate.module}#${candidate.name} ok=${result.ok} passed=${result.passed} failed=${result.failed}`,
    );
    return result;
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

function invokeTestRunner(
  dir: string,
  options: RunTestsOptions,
  hasTests: boolean,
  framework: "vitest" | "jest",
  nameFilter?: string,
): Promise<TestRunResult> {
  const cwd = options.cwd ?? process.cwd();
  const timeoutMs = options.timeoutMs ?? 60_000;
  // Both runners emit a JSON report with the same top-level
  // numPassedTests / numFailedTests shape, so parseVitestJson handles
  // both. The CLI surface differs slightly.
  const args =
    framework === "jest"
      ? ["jest", "--json", "--rootDir", dir]
      : ["vitest", "run", "--reporter=json", "--root", dir];
  if (nameFilter) {
    args.push("--testNamePattern", nameFilter);
  }
  return new Promise((resolve) => {
    const child = spawn("npx", args, { cwd, env: process.env });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (d) => (stdout += d.toString()));
    child.stderr.on("data", (d) => (stderr += d.toString()));
    const timer = setTimeout(() => {
      child.kill("SIGKILL");
    }, timeoutMs);
    child.on("close", () => {
      clearTimeout(timer);
      const parsed = parseVitestJson(stdout);
      const output = buildTestOutput(parsed, stderr, hasTests);
      // If the target function has no tests declared, a 0/0 result is a
      // legitimate "no contract to violate" — treat as ok. Otherwise
      // 0/0 usually means the runner crashed before any test executed.
      const ok = parsed
        ? parsed.failed === 0 && (parsed.passed > 0 || !hasTests)
        : false;
      resolve({
        ok,
        passed: parsed?.passed ?? 0,
        failed: parsed?.failed ?? 0,
        output: output.slice(-4000),
        failingTestNames: parsed?.failingTestNames ?? [],
        fullFailureMessages: parsed?.fullFailureMessages ?? new Map(),
      });
    });
  });
}

/**
 * Scan stderr for well-known error markers and return the matching
 * lines. We surface these explicitly because the 800-char `stderr tail`
 * can push the actual diagnostic off-screen when noise (deprecation
 * warnings, long stack frames, vitest's own banner) comes after the
 * error line.
 */
export function extractStderrDiagnostic(stderr: string): string {
  if (!stderr) return "";
  const markers =
    /^.*\b(SyntaxError|TypeError|ReferenceError|RangeError|URIError|EvalError|Error \[ERR_[A-Z_]+\]):.*$/gm;
  const hits = stderr.match(markers);
  if (!hits || hits.length === 0) return "";
  // Dedupe in order, cap at a handful so a repeating error doesn't
  // dominate the prompt.
  const seen = new Set<string>();
  const lines: string[] = [];
  for (const h of hits) {
    const line = h.trim();
    if (seen.has(line)) continue;
    seen.add(line);
    lines.push(line);
    if (lines.length >= 4) break;
  }
  return lines.join("\n");
}

/**
 * Assemble the test-output blob fed back to the Implementer. Distinguishes
 * three cases:
 *   1. 0/0 + hasTests — the test FILE didn't load (vitest reported no
 *      tests ran). Leads with an explicit "TEST FILE DID NOT LOAD"
 *      banner so the Implementer knows it's a compile/import error,
 *      not an assertion failure.
 *
 *      INVARIANT: 0/0 means load failure (not a filtered-out test run)
 *      because `renderFunctionTestFile` always wraps tests in
 *      `describe(<fnName>)` and `runTests` filters with
 *      `^<fnName>\b` — the filter always matches at least the
 *      describe block. If that emitter convention ever changes, this
 *      banner's claim becomes unsound.
 *   2. Some tests ran (passed or failed counted) — emits the failure
 *      digest + counts + stderr tail as before.
 *   3. Parse failed entirely (non-null `parsed` required) — falls back
 *      to the raw stderr so the Implementer can still see something.
 */
export function buildTestOutput(
  parsed: VitestCounts | null,
  stderr: string,
  hasTests: boolean,
): string {
  if (!parsed) return stderr;
  const sections: string[] = [];
  if (hasTests && parsed.passed === 0 && parsed.failed === 0) {
    sections.push(
      "[TEST FILE DID NOT LOAD — no tests ran.]",
      "The test file or the function body likely has a syntax error,",
      "bad import, or top-level throw preventing the module from",
      "loading. Check the key error(s) below and revise the body",
      "(and/or tests) so the file compiles, then resubmit. This is",
      "NOT an assertion failure.",
    );
  } else if (parsed.failureDigest) {
    sections.push(`----- failures -----\n${parsed.failureDigest}`);
  }
  // Surface the first few error lines near the top so they survive
  // even when the 800-char stderr-tail window misses them.
  const keyErrors = extractStderrDiagnostic(stderr);
  if (keyErrors) {
    sections.push(`----- key errors -----\n${keyErrors}`);
  }
  sections.push(
    `----- counts -----\npassed=${parsed.passed} failed=${parsed.failed}`,
  );
  if (stderr.trim().length > 0) {
    sections.push(`----- stderr tail -----\n${stderr.slice(-800)}`);
  }
  return sections.join("\n");
}

export interface VitestCounts {
  passed: number;
  failed: number;
  /** First-line assertion errors per failing test, joined for prompt feedback. */
  failureDigest: string;
  /** Fully-qualified names of failing tests (sorted, deduped). */
  failingTestNames: string[];
  /** Map of test name → full failure message (including stack trace). */
  fullFailureMessages: Map<string, string>;
}

function parseVitestJson(stdout: string): VitestCounts | null {
  const start = stdout.indexOf("{");
  if (start < 0) return null;
  try {
    const json = JSON.parse(stdout.slice(start));
    let passed = 0;
    let failed = 0;
    const failures: string[] = [];
    const failingNames = new Set<string>();
    const fullFailureMessages = new Map<string, string>();
    const results = Array.isArray(json.testResults) ? json.testResults : [];
    for (const file of results) {
      for (const t of file.assertionResults ?? []) {
        if (t.status === "passed") passed++;
        else if (t.status === "failed") {
          failed++;
          const title = String(
            t.fullName ?? t.title ?? t.ancestorTitles?.join(" > ") ?? "(test)",
          );
          failingNames.add(title);
          const msgs = Array.isArray(t.failureMessages) ? t.failureMessages : [];
          const raw = (msgs[0] ?? "").toString();
          if (raw) fullFailureMessages.set(title, raw);
          const firstLine = raw.split("\n")[0].slice(0, 240);
          failures.push(`✗ ${title}: ${firstLine || "(no failure message)"}`);
        }
      }
    }
    if (typeof json.numPassedTests === "number") passed = json.numPassedTests;
    if (typeof json.numFailedTests === "number") failed = json.numFailedTests;
    return {
      passed,
      failed,
      failureDigest: failures.slice(0, 20).join("\n"),
      failingTestNames: [...failingNames].sort(),
      fullFailureMessages,
    };
  } catch {
    return null;
  }
}
